name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: 56Wdu8fQZxiIKEBDmNpCMwx6yViV0Mo3:61e62d55973c5bb5733f232e
          oas-file-path: "./v1.json"
